version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: dj_app
    build: .
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgres/data
